### ISSUE TITLE
【Use】Windows Docker 部署报错

### ISSUE THREAD

**Issue by longmeidao** [rao-pics/core#140]
```
2023-04-27 00:37:24 raopics-api-1    | node:events:491
2023-04-27 00:37:24 raopics-api-1    |       throw er; // Unhandled 'error' event
2023-04-27 00:37:24 raopics-api-1    |       ^
2023-04-27 00:37:24 raopics-api-1    | 
2023-04-27 00:37:24 raopics-api-1    | Error: EIO: i/o error, scandir '/library/images/LGXTM1HKR0AGH.info'
2023-04-27 00:37:24 raopics-api-1    | Emitted 'error' event on FSWatcher instance at:
2023-04-27 00:37:24 raopics-api-1    |     at FSWatcher._handleError (/app/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/index.js:647:10)
2023-04-27 00:37:24 raopics-api-1    |     at NodeFsHandler._boundHandleError (/app/node_modules/.pnpm/chokidar@3.5.3/node_modules/chokidar/lib/nodefs-handler.js:303:43)
2023-04-27 00:37:24 raopics-api-1    |     at ReaddirpStream.emit (node:events:513:28)
2023-04-27 00:37:24 raopics-api-1    |     at emitErrorNT (node:internal/streams/destroy:151:8)
2023-04-27 00:37:24 raopics-api-1    |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
2023-04-27 00:37:24 raopics-api-1    |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2023-04-27 00:37:24 raopics-api-1    |   errno: -5,
2023-04-27 00:37:24 raopics-api-1    |   code: 'EIO',
2023-04-27 00:37:24 raopics-api-1    |   syscall: 'scandir',
2023-04-27 00:37:24 raopics-api-1    |   path: '/library/images/LGXTM1HKR0AGH.info'
2023-04-27 00:37:24 raopics-api-1    | }
2023-04-27 00:37:24 raopics-api-1    | 
2023-04-27 00:37:24 raopics-api-1    | Node.js v19.9.0
1970-01-01 08:00:00 raopics-api-1 exited with code 1
```

具体表现是，网页能读出库里的文件夹，但一张图片也读不出来。

**Comment by meetqy** [comment]
尝试看看：
* 在 images 中 搜索一下这个文件夹 `LGXTM1HKR0AGH.info` 看下原图是否存在。
* 如果存在，看下里面的metadata.json中name 是否和原图名称一样

正常的应该是这样的

<img width="899" alt="image" src="https://user-images.githubusercontent.com/18411315/234818554-987d8fba-4245-4d96-b093-175c76054343.png">

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/18411315/234818662-a35f1009-e011-46aa-99bf-92db409fb560.png">

我今天刚好遇到了这个问题，哈哈

**Comment by longmeidao** [comment]
昨晚回去再试了下，发现又复现不了这个报错了，没有任何报错但是没读到任何数据......

刚刚又试了在 Mac 上部署，还是有问题：

```
2023-04-28 11:33:11 raopics-api-1    | [03:33:11.429] INFO (1): Start transform 🛫
2023-04-28 11:33:11 raopics-api-1    | /app/node_modules/.pnpm/fs-extra@11.1.0/node_modules/fs-extra/lib/util/stat.js:84
2023-04-28 11:33:11 raopics-api-1    |       throw new Error(`Cannot overwrite directory '${dest}' with non-directory '${src}'.`)
2023-04-28 11:33:11 raopics-api-1    |             ^
2023-04-28 11:33:11 raopics-api-1    | 
2023-04-28 11:33:11 raopics-api-1    | Error: Cannot overwrite directory '/library/raopics.db' with non-directory '/app/packages/prisma-client/prisma/default.db'.
2023-04-28 11:30:01 raopics-nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
2023-04-28 11:30:01 raopics-nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
2023-04-28 11:30:01 raopics-nginx-1  | 2023/04/28 03:30:01 [notice] 1#1: using the "epoll" event method
2023-04-28 11:33:11 raopics-api-1    |     at Object.checkPathsSync (/app/node_modules/.pnpm/fs-extra@11.1.0/node_modules/fs-extra/lib/util/stat.js:84:13)
2023-04-28 11:30:01 raopics-nginx-1  | 2023/04/28 03:30:01 [notice] 1#1: nginx/1.23.4
2023-04-28 11:33:11 raopics-api-1    |     at Object.copySync (/app/node_modules/.pnpm/fs-extra@11.1.0/node_modules/fs-extra/lib/copy/copy-sync.js:27:38)
2023-04-28 11:33:11 raopics-api-1    |     at Module.f [as getPrisma] (/app/packages/prisma-client/dist/index.js:1:515)
2023-04-28 11:33:11 raopics-api-1    |     at Z (/app/packages/transform-eagle/dist/index.js:1:4880)
2023-04-28 11:33:11 raopics-api-1    |     at c (/app/packages/use/dist/index.js:1:187)
2023-04-28 11:33:11 raopics-api-1    |     at file:///app/docker/index.mjs:5:1
2023-04-28 11:33:11 raopics-api-1    |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
2023-04-28 11:33:11 raopics-api-1    | 
2023-04-28 11:33:11 raopics-api-1    | Node.js v19.9.0
```

**Comment by meetqy** [comment]
看下你的eagle library 地址，docker-compose.yml 配置

**Comment by meetqy** [comment]
[raopics.db.zip](https://github.com/rao-pics/core/files/11349619/raopics.db.zip)

额，docker好像吧db文件当做 文件夹来创建了， 你吧这个文件解压，放到eagle的library中。重启docker试试

**Comment by longmeidao** [comment]
应该是对应的：
<img width="465" alt="image" src="https://user-images.githubusercontent.com/42052392/235049383-47a09f5c-a3c7-4e19-8a75-283e63eaf8d6.png">

docker-compose.yml 配置：
```
    volumes:
      # 本地挂载library地址
      - /Users/longmeidao/Downloads/pixiv.library/images:/library/images:ro
      - /Users/longmeidao/Downloads/pixiv.library/metadata.json:/library/metadata.json:ro
      - /Users/longmeidao/Downloads/pixiv.library/tags.json:/library/tags.json:ro
      - /Users/longmeidao/Downloads/pixiv.library/raopics.db:/library/raopics.db
```

---

Update:
```
    environment:
      LIBRARY: /library # volumes中的地址
```
这个改成 `/pixiv.library` 就不报错了，但是就读不到任何数据了，也没有报错...

**Comment by meetqy** [comment]
```
volumes:
  # 本地挂载library地址
  - /Users/longmeidao/Downloads/pixiv.library/images:/library/images:ro
  - /Users/longmeidao/Downloads/pixiv.library/metadata.json:/library/metadata.json:ro
  - /Users/longmeidao/Downloads/pixiv.library/tags.json:/library/tags.json:ro
  - /Users/longmeidao/Downloads/pixiv.library/raopics.db:/library/raopics.db
```

改为

```
volumes: 
 - /Users/longmeidao/Downloads/pixiv.library:/library
```

这个是没问题的，他对应的是 volumes `:` 后面的这个 /library

```
environment:
  LIBRARY: /library # volumes中的地址
```

**Comment by meetqy** [comment]
2种方法可以试试：

一：

```
  api:
    tty: true
    build: ./
    environment:
      LIBRARY: /library # volumes中的地址
      PORT: 9600
    volumes:
      - /Users/longmeidao/Downloads/pixiv.library:/library
```

然后重启docker，但是图片过多的话，CPU会飙升。

第二种将这复制到你的`/Users/longmeidao/Downloads/pixiv.library`地址中。

> [raopics.db.zip](https://github.com/rao-pics/core/files/11349619/raopics.db.zip)

volumes 还是这样配置

```
volumes:
  # 本地挂载library地址
  - /Users/longmeidao/Downloads/pixiv.library/images:/library/images:ro
  - /Users/longmeidao/Downloads/pixiv.library/metadata.json:/library/metadata.json:ro
  - /Users/longmeidao/Downloads/pixiv.library/tags.json:/library/tags.json:ro
  - /Users/longmeidao/Downloads/pixiv.library/raopics.db:/library/raopics.db
```

**Comment by longmeidao** [comment]
感谢，第一种办法成功了。

**Comment by longmeidao** [comment]
但是这个 `raopics.db` 的更新规则是什么，我的库里现在有大约 9000 张图片，但它更新到 2000 多张就不动了😂

**Comment by meetqy** [comment]
你现在可以把 volumes 改回去，应该就不会报错了

```
volumes:
  # 本地挂载library地址
  - /Users/longmeidao/Downloads/pixiv.library/images:/library/images:ro
  - /Users/longmeidao/Downloads/pixiv.library/metadata.json:/library/metadata.json:ro
  - /Users/longmeidao/Downloads/pixiv.library/tags.json:/library/tags.json:ro
  - /Users/longmeidao/Downloads/pixiv.library/raopics.db:/library/raopics.db
```

**Comment by longmeidao** [comment]
> log 不动的话，你可以看 stats,只要CPU在跑就在执行

CPU 是 0% USAGE...

**Comment by meetqy** [comment]
那删除 image 和 container 里的 raopics-api ，把配置改为

```
volumes:
  # 本地挂载library地址
  - /Users/longmeidao/Downloads/pixiv.library/images:/library/images:ro
  - /Users/longmeidao/Downloads/pixiv.library/metadata.json:/library/metadata.json:ro
  - /Users/longmeidao/Downloads/pixiv.library/tags.json:/library/tags.json:ro
  - /Users/longmeidao/Downloads/pixiv.library/raopics.db:/library/raopics.db
```

重新执行 `docker compose up -d`

**Comment by meetqy** [comment]
已经修改了，重新拉一下项目，然后按照readme重新执行就可以了

**Comment by longmeidao** [comment]
似乎还是有问题：

```
2023-04-28 17:19:58 raopics-api-1    | TypeError: Cannot read properties of undefined (reading 'replace')
2023-04-28 17:19:58 raopics-api-1    |     at E (/app/packages/transform-eagle/dist/index.js:1:1748)
2023-04-28 17:19:58 raopics-api-1    |     at invokeFunc (/app/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:10401:23)
2023-04-28 17:19:58 raopics-api-1    |     at trailingEdge (/app/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:10450:18)
2023-04-28 17:19:58 raopics-api-1    |     at Timeout.timerExpired [as _onTimeout] (/app/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:10438:18)
2023-04-28 17:19:58 raopics-api-1    |     at listOnTimeout (node:internal/timers:573:17)
2023-04-28 17:19:58 raopics-api-1    |     at process.processTimers (node:internal/timers:514:7)
2023-04-28 17:19:58 raopics-api-1    | 
2023-04-28 17:19:58 raopics-api-1    | Node.js v20.0.0
1970-01-01 08:00:00 raopics-api-1 exited with code 1
```
